PROD_SONG_DIRECTORY = "../data/prod/songs/mp3"
DEMO_SONG_DIRECTORY = "../data/demo/songs_demo"
PROD_DEMUCS_DIRECTORY = "../data/prod/demucs/mdx_q"
DEMO_DEMUCS_DIRECTORY = "../data/demo/demucs_demo/mdx_q"
PROD_JSON_DIRECTORY = "../data/prod/allin1_formatted"
DEMO_JSON_DIRECTORY = "../data/demo/allin1_demo"
PROD_MIDI_DIRECTORY = "../data/prod/midi"
DEMO_MIDI_DIRECTORY = "../data/demo/midi_demo"
